[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
branch = true
source =["openapi_spec_validator"]

[tool.coverage.xml]
output = "reports/coverage.xml"

[tool.poetry]
name = "openapi-spec-validator"
version = "0.3.2"
description = "OpenAPI 2.0 (aka Swagger) and OpenAPI 3.0 spec validator"
authors = ["Artur Maciag <maciag.artur@gmail.com>"]
license = "Apache License, Version 2.0"
readme = "README.rst"
repository = "https://github.com/p1c2u/openapi-spec-validator"
keywords = ["openapi", "swagger", "schema"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries"
]

[tool.poetry.dependencies]
python = ">= 2.7, != 3.0.*, != 3.1.*, != 3.2.*, != 3.3.*, != 3.4.*"
jsonschema = ">=3.2.0, <4.0.0"
pyrsistent = "<0.17.0"
PyYAML = ">=5.1"
six = "*"
pathlib2 = {version = "*", python = "~2.7"}
openapi-schema-validator = "<0.2.0"
requests = {version = "*", optional = true}

[tool.poetry.extras]
dev = ["pre-commit"]
requests = ["requests"]

[tool.poetry.dev-dependencies]
mock = {version = "*", python = "~2.7"}
pre-commit =  {version = "*", optional = true}
pytest = "=3.5.0"
pytest-flake8 = "=1.0.7"
pytest-cov = "=2.5.1"
tox = "*"

[tool.poetry.scripts]
openapi-spec-validator = "openapi_spec_validator.__main__:main"

[tool.pytest.ini_options]
addopts = """
--capture=no
--verbose
--showlocals
--junitxml=reports/junit.xml
--cov=openapi_spec_validator
--cov-report=term-missing
--cov-report=xml
"""

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
force_single_line = true
